/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCommunityInfoRouteImport } from './routes/_app.community-info'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppLoginRouteImport } from './routes/_app.login'
import { Route as AppLostStraysRouteImport } from './routes/_app.lost-strays'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRegisterRouteImport } from './routes/_app.register'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppSignupsClosedRouteImport } from './routes/_app.signups-closed'
import { Route as AppStrayActivitiesRouteImport } from './routes/_app.stray-activities'
import { Route as AppStrayAdoptionsRouteImport } from './routes/_app.stray-adoptions'
import { Route as AppStrayRegistrationRouteImport } from './routes/_app.stray-registration'
import { Route as AppStraysMapRouteImport } from './routes/_app.strays-map'
import { Route as AppForumIndexRouteImport } from './routes/_app.forum.index'
import { Route as AppNewsIndexRouteImport } from './routes/_app.news.index'
import { Route as AppNewsArticleIdRouteImport } from './routes/_app.news.$articleId'
import { Route as AppForumThreadThreadIdRouteImport } from './routes/_app.forum.thread.$threadId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityInfoRoute = AppCommunityInfoRouteImport.update({
  id: '/community-info',
  path: '/community-info',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLostStraysRoute = AppLostStraysRouteImport.update({
  id: '/lost-strays',
  path: '/lost-strays',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupsClosedRoute = AppSignupsClosedRouteImport.update({
  id: '/signups-closed',
  path: '/signups-closed',
  getParentRoute: () => AppRoute,
} as any)
const AppStrayActivitiesRoute = AppStrayActivitiesRouteImport.update({
  id: '/stray-activities',
  path: '/stray-activities',
  getParentRoute: () => AppRoute,
} as any)
const AppStrayAdoptionsRoute = AppStrayAdoptionsRouteImport.update({
  id: '/stray-adoptions',
  path: '/stray-adoptions',
  getParentRoute: () => AppRoute,
} as any)
const AppStrayRegistrationRoute = AppStrayRegistrationRouteImport.update({
  id: '/stray-registration',
  path: '/stray-registration',
  getParentRoute: () => AppRoute,
} as any)
const AppStraysMapRoute = AppStraysMapRouteImport.update({
  id: '/strays-map',
  path: '/strays-map',
  getParentRoute: () => AppRoute,
} as any)
const AppForumIndexRoute = AppForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsIndexRoute = AppNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsArticleIdRoute = AppNewsArticleIdRouteImport.update({
  id: '/news/$articleId',
  path: '/news/$articleId',
  getParentRoute: () => AppRoute,
} as any)
const AppForumThreadThreadIdRoute = AppForumThreadThreadIdRouteImport.update({
  id: '/forum/thread/$threadId',
  path: '/forum/thread/$threadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/chat': typeof AppChatRoute
  '/community-info': typeof AppCommunityInfoRoute
  '/feedback': typeof AppFeedbackRoute
  '/login': typeof AppLoginRoute
  '/lost-strays': typeof AppLostStraysRoute
  '/map': typeof AppMapRoute
  '/profile': typeof AppProfileRoute
  '/register': typeof AppRegisterRoute
  '/report': typeof AppReportRoute
  '/signups-closed': typeof AppSignupsClosedRoute
  '/stray-activities': typeof AppStrayActivitiesRoute
  '/stray-adoptions': typeof AppStrayAdoptionsRoute
  '/stray-registration': typeof AppStrayRegistrationRoute
  '/strays-map': typeof AppStraysMapRoute
  '/news/$articleId': typeof AppNewsArticleIdRoute
  '/forum/': typeof AppForumIndexRoute
  '/news/': typeof AppNewsIndexRoute
  '/forum/thread/$threadId': typeof AppForumThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/chat': typeof AppChatRoute
  '/community-info': typeof AppCommunityInfoRoute
  '/feedback': typeof AppFeedbackRoute
  '/login': typeof AppLoginRoute
  '/lost-strays': typeof AppLostStraysRoute
  '/map': typeof AppMapRoute
  '/profile': typeof AppProfileRoute
  '/register': typeof AppRegisterRoute
  '/report': typeof AppReportRoute
  '/signups-closed': typeof AppSignupsClosedRoute
  '/stray-activities': typeof AppStrayActivitiesRoute
  '/stray-adoptions': typeof AppStrayAdoptionsRoute
  '/stray-registration': typeof AppStrayRegistrationRoute
  '/strays-map': typeof AppStraysMapRoute
  '/': typeof AppIndexRoute
  '/news/$articleId': typeof AppNewsArticleIdRoute
  '/forum': typeof AppForumIndexRoute
  '/news': typeof AppNewsIndexRoute
  '/forum/thread/$threadId': typeof AppForumThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/community-info': typeof AppCommunityInfoRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/lost-strays': typeof AppLostStraysRoute
  '/_app/map': typeof AppMapRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/report': typeof AppReportRoute
  '/_app/signups-closed': typeof AppSignupsClosedRoute
  '/_app/stray-activities': typeof AppStrayActivitiesRoute
  '/_app/stray-adoptions': typeof AppStrayAdoptionsRoute
  '/_app/stray-registration': typeof AppStrayRegistrationRoute
  '/_app/strays-map': typeof AppStraysMapRoute
  '/_app/': typeof AppIndexRoute
  '/_app/news/$articleId': typeof AppNewsArticleIdRoute
  '/_app/forum/': typeof AppForumIndexRoute
  '/_app/news/': typeof AppNewsIndexRoute
  '/_app/forum/thread/$threadId': typeof AppForumThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/community-info'
    | '/feedback'
    | '/login'
    | '/lost-strays'
    | '/map'
    | '/profile'
    | '/register'
    | '/report'
    | '/signups-closed'
    | '/stray-activities'
    | '/stray-adoptions'
    | '/stray-registration'
    | '/strays-map'
    | '/news/$articleId'
    | '/forum/'
    | '/news/'
    | '/forum/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/community-info'
    | '/feedback'
    | '/login'
    | '/lost-strays'
    | '/map'
    | '/profile'
    | '/register'
    | '/report'
    | '/signups-closed'
    | '/stray-activities'
    | '/stray-adoptions'
    | '/stray-registration'
    | '/strays-map'
    | '/'
    | '/news/$articleId'
    | '/forum'
    | '/news'
    | '/forum/thread/$threadId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/chat'
    | '/_app/community-info'
    | '/_app/feedback'
    | '/_app/login'
    | '/_app/lost-strays'
    | '/_app/map'
    | '/_app/profile'
    | '/_app/register'
    | '/_app/report'
    | '/_app/signups-closed'
    | '/_app/stray-activities'
    | '/_app/stray-adoptions'
    | '/_app/stray-registration'
    | '/_app/strays-map'
    | '/_app/'
    | '/_app/news/$articleId'
    | '/_app/forum/'
    | '/_app/news/'
    | '/_app/forum/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community-info': {
      id: '/_app/community-info'
      path: '/community-info'
      fullPath: '/community-info'
      preLoaderRoute: typeof AppCommunityInfoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lost-strays': {
      id: '/_app/lost-strays'
      path: '/lost-strays'
      fullPath: '/lost-strays'
      preLoaderRoute: typeof AppLostStraysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signups-closed': {
      id: '/_app/signups-closed'
      path: '/signups-closed'
      fullPath: '/signups-closed'
      preLoaderRoute: typeof AppSignupsClosedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stray-activities': {
      id: '/_app/stray-activities'
      path: '/stray-activities'
      fullPath: '/stray-activities'
      preLoaderRoute: typeof AppStrayActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stray-adoptions': {
      id: '/_app/stray-adoptions'
      path: '/stray-adoptions'
      fullPath: '/stray-adoptions'
      preLoaderRoute: typeof AppStrayAdoptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stray-registration': {
      id: '/_app/stray-registration'
      path: '/stray-registration'
      fullPath: '/stray-registration'
      preLoaderRoute: typeof AppStrayRegistrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/strays-map': {
      id: '/_app/strays-map'
      path: '/strays-map'
      fullPath: '/strays-map'
      preLoaderRoute: typeof AppStraysMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forum/': {
      id: '/_app/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof AppForumIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/': {
      id: '/_app/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof AppNewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/$articleId': {
      id: '/_app/news/$articleId'
      path: '/news/$articleId'
      fullPath: '/news/$articleId'
      preLoaderRoute: typeof AppNewsArticleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forum/thread/$threadId': {
      id: '/_app/forum/thread/$threadId'
      path: '/forum/thread/$threadId'
      fullPath: '/forum/thread/$threadId'
      preLoaderRoute: typeof AppForumThreadThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppCommunityInfoRoute: typeof AppCommunityInfoRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppLoginRoute: typeof AppLoginRoute
  AppLostStraysRoute: typeof AppLostStraysRoute
  AppMapRoute: typeof AppMapRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppReportRoute: typeof AppReportRoute
  AppSignupsClosedRoute: typeof AppSignupsClosedRoute
  AppStrayActivitiesRoute: typeof AppStrayActivitiesRoute
  AppStrayAdoptionsRoute: typeof AppStrayAdoptionsRoute
  AppStrayRegistrationRoute: typeof AppStrayRegistrationRoute
  AppStraysMapRoute: typeof AppStraysMapRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNewsArticleIdRoute: typeof AppNewsArticleIdRoute
  AppForumIndexRoute: typeof AppForumIndexRoute
  AppNewsIndexRoute: typeof AppNewsIndexRoute
  AppForumThreadThreadIdRoute: typeof AppForumThreadThreadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppCommunityInfoRoute: AppCommunityInfoRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppLoginRoute: AppLoginRoute,
  AppLostStraysRoute: AppLostStraysRoute,
  AppMapRoute: AppMapRoute,
  AppProfileRoute: AppProfileRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppReportRoute: AppReportRoute,
  AppSignupsClosedRoute: AppSignupsClosedRoute,
  AppStrayActivitiesRoute: AppStrayActivitiesRoute,
  AppStrayAdoptionsRoute: AppStrayAdoptionsRoute,
  AppStrayRegistrationRoute: AppStrayRegistrationRoute,
  AppStraysMapRoute: AppStraysMapRoute,
  AppIndexRoute: AppIndexRoute,
  AppNewsArticleIdRoute: AppNewsArticleIdRoute,
  AppForumIndexRoute: AppForumIndexRoute,
  AppNewsIndexRoute: AppNewsIndexRoute,
  AppForumThreadThreadIdRoute: AppForumThreadThreadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
